import { useEffect, useState } from "react";
import PropTypes from "prop-types";
import { Link } from "react-router-dom";
import { FiBriefcase, FiCalendar, FiCheckCircle, FiClipboard, FiCreditCard, FiFileText, FiSearch, FiTrendingUp } from "react-icons/fi";
import { toast } from "react-toastify";
import Navbar from "./Navbar";
import EmptyState from "../components/EmptyState";
import StatusBadge from "../components/StatusBadge";
import apiRequest from "../utils/api";
import getHeader from "../utils/header";
import "../css/DashboardHome.css";

const money = (value) => `₹${Number(value || 0).toLocaleString("en-IN", { minimumFractionDigits: 0, maximumFractionDigits: 2 })}`;
const groups = [["events", "Events"], ["proforma", "Proforma"], ["invoices", "Tax Invoices"], ["payments", "Payments"], ["payouts", "Payouts"], ["work", "Daily Work"]];
const kpiIcons = { "Active Events": FiBriefcase, "Upcoming Events": FiCalendar, "Pending Tasks": FiCheckCircle, "Today's Work": FiClipboard, Outstanding: FiCreditCard, Received: FiTrendingUp, "Pending Payouts": FiCreditCard, "This Month Invoices": FiFileText };

const DashboardHome = () => {
	const [summary, setSummary] = useState(null);
	const [query, setQuery] = useState("");
	const [results, setResults] = useState(null);
	const [error, setError] = useState(false);
	useEffect(() => { apiRequest("/api/dashboard/summary", { headers: getHeader() }).then((response) => setSummary(response.data)).catch(() => setError(true)); }, []);
	useEffect(() => { const timer = setTimeout(() => { if (query.trim().length < 2) return setResults(null); apiRequest(`/api/dashboard/search?q=${encodeURIComponent(query)}`, { headers: getHeader() }).then((response) => setResults(response.data)).catch(() => toast.error("Search unavailable")); }, 250); return () => clearTimeout(timer); }, [query]);
	const kpis = summary ? [["Active Events", summary.kpis.activeEvents], ["Upcoming Events", summary.kpis.upcomingEvents], ["Pending Tasks", summary.kpis.pendingTasks], ["Today's Work", summary.kpis.todaysWork], ["Outstanding", money(summary.kpis.totalOutstanding)], ["Received", money(summary.kpis.totalReceived)], ["Pending Payouts", summary.kpis.pendingPayouts], ["This Month Invoices", money(summary.kpis.currentMonthInvoiceValue)]] : [];
	return <><Navbar /><main className="operations-dashboard"><header className="operations-header"><div><p className="eyebrow">Operations overview</p><h1>Dashboard</h1><p>{new Date().toLocaleDateString(undefined, { dateStyle: "full" })}</p></div><div className="dashboard-actions"><Link className="model-cancel" to="/events">View Events</Link><Link className="model-submit" to="/events">Create Event</Link></div></header><div className="global-search"><FiSearch className="search-icon" /><input aria-label="Global search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search events, invoices, payments, payouts, work" />{results && <div className="search-results">{groups.flatMap(([key, label]) => (results[key] || []).map((item) => <Link key={`${key}-${item._id}`} to={item.eventId ? `/events/${item.eventId}` : key === "events" ? `/events/${item._id}` : "/"}><strong>{label}</strong> {item.eventName || item.piNumber || item.invoiceNumber || item.referenceNumber || item.vendorName || item.workDescription || item._id}</Link>))}{!groups.some(([key]) => results[key]?.length) && <EmptyState title="No results found" description="Try searching for an event, invoice, payment or payout." />}</div>}</div>{error ? <section className="dashboard-message"><EmptyState title="Unable to load dashboard" description="Your data could not be loaded right now." action={<button className="model-submit" onClick={() => window.location.reload()}>Retry</button>} /></section> : !summary ? <section className="dashboard-message"><p>Loading dashboard...</p></section> : <><section className="kpi-grid">{kpis.map(([label, value]) => { const Icon = kpiIcons[label]; return <div className="kpi-card" key={label}><span className="kpi-icon"><Icon /></span><div><span>{label}</span><strong>{value}</strong></div></div>; })}</section><section className="dashboard-grid"><DashboardList title="Upcoming Events" items={summary.upcomingEvents} emptyTitle="No upcoming events" emptyDescription="Create your first event to start tracking operations." action={<Link className="model-submit" to="/events">Create Event</Link>} /><DashboardList title="Active Events" items={summary.activeEvents} emptyTitle="No active events" emptyDescription="Events marked ongoing will appear here." /><DashboardList title="Outstanding Invoices" items={summary.outstandingInvoices} emptyTitle="No outstanding invoices" emptyDescription="Your receivables are currently clear." moneyField="outstandingAmount" /><DashboardList title="Today's Work" items={summary.todaysWork} emptyTitle="No work logged today" emptyDescription="Keep the team aligned by logging today's work." action={<Link className="model-submit" to="/daily-work">Add Work</Link>} /><DashboardList title="Recent Activity" items={summary.recentActivity} emptyTitle="Activity will appear here" emptyDescription="Actions across your workspace will be recorded here." activity /></section></>}</main></>;
};
const DashboardList = ({ title, items, emptyTitle, emptyDescription, action, moneyField, activity }) => <section className="dashboard-panel"><div className="panel-heading"><h2>{title}</h2><Link to={title.includes("Event") ? "/events" : title.includes("Work") ? "/daily-work" : "/"}>View all</Link></div>{items.length ? items.map((item) => <Link className="dashboard-row" to={item.eventId || item._id && activity ? `/events/${item.eventId}` : item._id && title.includes("Event") ? `/events/${item._id}` : "/"} key={item._id}><span className="dashboard-row-main"><strong>{activity ? item.description : item.event?.eventName || item.eventName || item.piNumber || item.workDescription || item._id}</strong><small>{activity ? new Date(item.createdAt).toLocaleString() : item.event?.city || item.city || item.event?.clientName || item.clientName || item.date || "-"}</small></span><span className="dashboard-row-side">{moneyField ? money(item[moneyField]) : item.status ? <StatusBadge status={item.status} /> : item.event?.eventDate || item.eventDate || ""}</span></Link>) : <EmptyState title={emptyTitle} description={emptyDescription} action={action} />}</section>;
DashboardList.propTypes = { title: PropTypes.string.isRequired, items: PropTypes.arrayOf(PropTypes.object).isRequired, emptyTitle: PropTypes.string.isRequired, emptyDescription: PropTypes.string.isRequired, action: PropTypes.node, moneyField: PropTypes.string, activity: PropTypes.bool };
export default DashboardHome;
